apache/phoenix

phoenix-core/src/it/java/org/apache/phoenix/monitoring/GlobalPhoenixMetricsTestSink.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixMetricsDisabledIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixMetricsIT.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/GlobalClientMetrics.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/GlobalMetricImpl.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/GlobalMetricRegistriesAdapter.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/NoOpGlobalMetricImpl.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java, phoenix-core/src/test/resources/hadoop-metrics2.properties
=> PHOENIX-3655 Global Phoenix Client Metrics for PQS

phoenix-core/src/main/java/org/apache/phoenix/query/KeyRange.java, phoenix-core/src/main/java/org/apache/phoenix/util/ScanUtil.java, phoenix-core/src/test/java/org/apache/phoenix/query/KeyRangeMoreTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/SplitKeyRangesByBoundariesTest.java
Which problem(s) does it fix and how? What does this PR add?
Explain what should be set-up first in order to get the review started. Which page has to be viewed etc.
If this PR changes something that concerns UI changes, please post before and after screenshots here.
If you have any documents that have anything to do with this PR.
- Does this require a blog post?
- Does this require a knowledge base update?
- Does support need training for this?
- Does this has to be communicated to partners?
=> Add common utility function ScanUtil.splityKeyRangesByBoundaries()

phoenix-pherf/src/main/java/org/apache/phoenix/pherf/result/impl/CSVFileResultHandler.java
CSVFileResultHandler closes CSVParser which could cause NPE if creating CSVParser causes IOException and original IOException can be lost
=> PHOENIX-5379 : Avoid possible NPE while closing CSVParser

phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java
"query" was misspelled to "qeuery" in ConnectionQueryServicesImpl warning logging:
https://github.com/apache/phoenix/blob/62387ee3c55f8be1947161bc9d501b1867cc24f1/phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java#L443
=> PHOENIX-5408: Typo in ConnectionQueryServicesImpl Warning Logging

phoenix-core/src/test/java/org/apache/phoenix/expression/RoundFloorCeilExpressionsTest.java
=> PHOENIX-5130 removed 'static' keyword from 'private static enum'

phoenix-core/src/it/java/org/apache/phoenix/end2end/QueryDatabaseMetaDataIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TenantSpecificTablesDDLIT.java, phoenix-core/src/main/antlr3/PhoenixSQL.g, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixDatabaseMetaData.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ParseNodeFactory.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ShowSchemasStatement.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ShowStatement.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ShowTablesStatement.java, phoenix-core/src/main/java/org/apache/phoenix/util/QueryUtil.java, phoenix-core/src/test/java/org/apache/phoenix/parse/QueryParserTest.java, phoenix-pherf/src/main/java/org/apache/phoenix/pherf/util/PhoenixUtil.java
This patch adds new SQL grammar like following
- SHOW SCHEMAS [like '<pattern>']
- SHOW TABLES [IN <schema>] [like '<pattern']
Example invocations:
- show schemas
- show scemas like 'SYS%'
- show tables
- show tables in SYSTEM
- show tables in SYSTEM like 'CAT%'
The current way of fetching this information is by using
!tables and !schemas via sqlline JDBC support but that is
not flexible enough for the end users to add more fitlers.
This approach is more inline with what other databases do.
Added test coverage in parser tests and core e2e tests.
=> PHOENIX-5543: Implement SHOW TABLES/SCHEMAS sql commands

phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexToolForNonTxGlobalIndexIT.java
Tests are creating a new conf object and setting the
INDEX_REBUILD_PAGE_SIZE_IN_ROWS parameter. Pass that conf object to the
IndexTool.
=> PHOENIX-6183 Page size tests are not propagating test override valuees to server

phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexToolIT.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/PhoenixServerBuildIndexInputFormat.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexTool.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/util/PhoenixConfigurationUtil.java, phoenix-core/src/test/java/org/apache/phoenix/index/IndexToolTest.java, phoenix-core/src/test/java/org/apache/phoenix/mapreduce/util/PhoenixConfigurationUtilTest.java
Part of PHOENIX-6182
New option `-fi` or `--from-index` added. When specified, use the index table as the source for verification. Inly works with `-vBEFORE` and `-vONLY` options.
=> PHOENIX-6198 Add option to IndexTool to specify the source table for scan

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/ImmutableIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/MutableIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/DeleteCompiler.java
MutationState.join() ignores index rows in row count so totalRowCount calculated
will reflect the data table always and the index table only if the bestPlan
uses the index table. So ignore the other index tables when determining
the number of tables updated.
=> PHOENIX-6218 Rows deleted count is incorrect for immutable tables with indexes

phoenix-core/src/it/java/org/apache/phoenix/query/MaxConcurrentConnectionsIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/MutatingParallelIteratorFactory.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixConnection.java
https://issues.apache.org/jira/browse/PHOENIX-6078
=> PHOENIX-6078 Remove Internal Phoenix Connections from parent LinkedQueue when closed

phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java
=> PHOENIX-6086 : Avoid restoring snapshots of System tables

phoenix-core/src/it/java/org/apache/phoenix/end2end/DeleteIT.java, phoenix-core/src/main/java/org/apache/hadoop/hbase/PhoenixTagType.java, phoenix-core/src/main/java/org/apache/phoenix/call/CallRunner.java, phoenix-core/src/main/java/org/apache/phoenix/compile/DeleteCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/UngroupedAggregateRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixConnection.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core/src/test/java/org/apache/phoenix/compile/QueryOptimizerTest.java
Changes done in this PR: 
1. Added a new property in ConnectionQueryServices` phoenix.source.operation` The client will set this in Properties object to create the connection. This indicates the metadata about what is the source of the operation. for e.g. customer-delete, internal-service-delete, etc.
2. Changed MutationState and UngroupedAggregateRegionScanner to propagate the attribute from PhoenixConnection to mutation object
3. Added a method in  IndexRegionObserver to add the attribute from mutation object to cell as tags.
=> [PHOENIX-6213] Extend Cell Tags to Delete object to store source of operation.

phoenix-core/src/test/java/org/apache/phoenix/SystemExitRule.java, phoenix-core/src/test/java/org/apache/phoenix/TestJVMExit.java, phoenix-core/src/test/java/org/apache/phoenix/TestSecurityManager.java, phoenix-core/src/test/java/org/apache/phoenix/memory/MemoryManagerTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/BaseTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/ConnectionQueryServicesImplTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/ConnectionlessTest.java
=> PHOENIX-6275 : Handle JVM exit gracefully in tests

bin/readme.txt
the old sqlline manual url in homepage is invalid. Update to the new url address.
Related to https://issues.apache.org/jira/browse/PHOENIX-5888
=> PHOENIX-5888 [DOCS] update sqlline manual URL

phoenix-core/src/it/java/org/apache/phoenix/end2end/ConcurrentUpsertsWithoutIndexedColsIT.java
=> PHOENIX-6302 : De-flake ConcurrentUpsertsWithoutIndexedColsIT

phoenix-core/src/main/java/org/apache/phoenix/cache/TenantCacheImpl.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ExpressionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core/src/main/java/org/apache/phoenix/filter/RowKeyComparisonFilter.java, phoenix-core/src/main/java/org/apache/phoenix/hbase/index/covered/filter/ApplyAndFilterDeletesFilter.java, phoenix-core/src/main/java/org/apache/phoenix/hbase/index/covered/update/IndexUpdateManager.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RoundRobinResultIterator.java, phoenix-core/src/main/java/org/apache/phoenix/join/HashCacheFactory.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexScrutinyTool.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexUpgradeTool.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/main/java/org/apache/phoenix/schema/stats/StatisticsCollectionRunTracker.java
=> PHOENIX-6295 : Fix non-static inner classes for better memory utilization

phoenix-core/src/it/java/org/apache/phoenix/end2end/TableSnapshotReadsMapReduceIT.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/TableSnapshotResultIterator.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/PhoenixInputFormat.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/util/PhoenixConfigurationUtil.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/util/PhoenixMapReduceUtil.java
https://issues.apache.org/jira/browse/PHOENIX-6273
=> PHOENIX-6273: Add support to handle MR Snapshot restore externally

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/LocalIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereCompiler.java
See long discussion on Jira: https://issues.apache.org/jira/browse/PHOENIX-6400
=> PHOENIX-6400 Do no use local index with uncovered columns in the WHERE clause.

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/LocalIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ExplainTable.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/OrderedResultIterator.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RegionScannerFactory.java, phoenix-core/src/main/java/org/apache/phoenix/schema/types/PVarbinary.java
This works by passing down the filter expression as a scan attribute and evaluating it after the full tuple has been assembled by merging in columns from the main column family.
Please review this carefully, this is tricky stuff and I ran into a bunch of snags and unexpected details in the process.
=> PHOENIX-6402 Allow using local indexes with uncovered columns in the WHERE clause.

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/LocalIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ExplainTable.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RegionScannerFactory.java
See description in the jira.
The fix is relatively straight forward, if not particularly pretty:
- don't enforce the limit via a filter
- instead count the rows after the extraWhere filter has run for uncovered local index WHERE clauses
I added extra tests for this.
=> PHOENIX-6408 LIMIT on local index query with uncovered columns in the WHERE returns wrong result.

phoenix-core/src/it/java/org/apache/phoenix/end2end/CostBasedDecisionIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/LocalIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/MutableIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/ViewIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/join/HashJoinLocalIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ExplainPlanAttributes.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ExplainTable.java
=> PHOENIX-6409 Include local index uncovered columns merge in explain plan.

phoenix-core/src/it/java/org/apache/phoenix/end2end/MultiCfQueryExecIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ProjectionCompiler.java
See Jira.
SELECT * is generally broken with any table table mixes C and CF.C. (i.e. the same column name in the default and an explicit column family).
After spending a lot of time debugging, turns out the fix is pretty simple.
=> PHOENIX-6423 Wildcard queries fail with mixed default and explicit column families.

phoenix-core/src/it/java/org/apache/phoenix/end2end/MultiCfQueryExecIT.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/util/EncodedColumnsUtil.java
See Jira. In the SELECT CF1.* WHERE CF2.C ... cannot use the EncodedQualifiersColumnProjectionFilter since the number of qualifiers is not know (so the trackcolumns Bitset cannot be build ahead of time).
=> PHOENIX-6424 SELECT cf1.* FAILS with a WHERE clause including cf2.

phoenix-core/src/main/java/org/apache/phoenix/iterate/OrderedResultIterator.java
See Jira.
the OrderedResultIterator will store topN values in either a BufferedQueue or a SizeBoundQueue. Each limit the memory used to the passed thresholdBytes (default is 20MB), the BufferQueue will spool to disk when reaching that size, SizeBoundQueue will fail.
Hence we additionally limit the worst case memory consumption to thresholdBytes.
I noticed this when implementing limit and topN pushdown for the Trino Phoenix connector: https://github.com/trinodb/trino/pull/7490
=> PHOENIX-6436 OrderedResultIterator overestimates memory requirements.

bin/phoenix_utils.py, bin/sqlline.py, phoenix-assembly/pom.xml, phoenix-assembly/src/build/components/all-common-dependencies.xml, phoenix-assembly/src/build/components/all-common-jars.xml, phoenix-assembly/src/build/package-to-tar-all.xml, phoenix-client-parent/phoenix-client-embedded/pom.xml, pom.xml
Change-Id: I443593c18d412c4ccd2e137c6b2809863bc71bc8
=> PHOENIX-6378 Unbundle sqlline from phoenix-client

phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexRepairRegionScannerIT.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/IndexRepairRegionScanner.java
When verifying from index table to data table, there were 2 issues:
1. Data table region boundary keys were not being respected so the splits were happening only on the basis of per task max size.
2. The actual index mutation map was was not being split for every task but the data row keys were being split. This caused the tool to report extra index rows which were actually false positives.
=> PHOENIX-6476 Index tool when verifying from index to data doesn't correctly split page into tasks

phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKeyIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/WALAnnotationIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/GlobalIndexCheckerIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/BasePhoenixMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixTableLevelMetricsIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/UpsertCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/GlobalIndexRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/MetricType.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/MutationMetricQueue.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/TableClientMetrics.java, phoenix-core/src/main/java/org/apache/phoenix/schema/PTableImpl.java, phoenix-core/src/test/java/org/apache/phoenix/compile/QueryCompilerTest.java
=> Phoenix 6387 Conditional Updates

phoenix-core/src/it/java/org/apache/phoenix/end2end/BasePermissionsIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CreateSchemaIT.java, phoenix-core/src/main/antlr3/PhoenixSQL.g, phoenix-core/src/main/java/org/apache/phoenix/parse/CreateSchemaStatement.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryConstants.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/main/java/org/apache/phoenix/util/SchemaUtil.java, phoenix-core/src/test/java/org/apache/phoenix/parse/QueryParserTest.java
Almost a clean cherry pick of PHOENIX-4424 
https://github.com/apache/phoenix/commit/c075a17879309fe4def5a621951d72929fb10c3a
=> PHOENIX-6509 PHOENIX-4424 Allow users to create DEFAULT and HBASE Schema (Uppercase Schema Names)

phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKeyIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/WALAnnotationIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/GlobalIndexCheckerIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/BasePhoenixMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixTableLevelMetricsIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/UpsertCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/GlobalIndexRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/MetricType.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/MutationMetricQueue.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/TableClientMetrics.java, phoenix-core/src/main/java/org/apache/phoenix/schema/PTableImpl.java, phoenix-core/src/test/java/org/apache/phoenix/compile/QueryCompilerTest.java
=>  PHOENIX-6387: Conditional updates on tables with indexes

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/SaltedIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/TupleProjectionCompiler.java
See: https://issues.apache.org/jira/browse/PHOENIX-6604
Basically due to incorrect resolution of columns any index on a wildcard query * or count(*) will incorrectly be rejected for salted tables.
=> PHOENIX-6604 Allow using indexes for wildcard topN queries on salted tables

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/GlobalIndexCheckerIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/GlobalIndexOptimizationIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ExpressionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/FromCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/JoinCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ProjectionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/StatementContext.java, phoenix-core/src/main/java/org/apache/phoenix/compile/TupleProjectionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/GroupedAggregateRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/execute/BaseQueryPlan.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ExplainTable.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/NonAggregateRegionScannerFactory.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RegionScannerFactory.java, phoenix-core/src/main/java/org/apache/phoenix/optimize/QueryOptimizer.java, phoenix-core/src/main/java/org/apache/phoenix/schema/IndexDataColumnRef.java, phoenix-core/src/main/java/org/apache/phoenix/schema/TableRef.java, phoenix-core/src/main/java/org/apache/phoenix/util/IndexUtil.java, phoenix-core/src/main/java/org/apache/phoenix/util/ScanUtil.java
The Phoenix query optimizer does not use a global index for a query with the columns that are not covered by the global index if the query does not have the corresponding index hint for this index. With the index hint, the optimizer rewrites the query where the index is used within a subquery. With this subquery, the row keys of the index rows that satisfy the subquery are retrieved by the Phoenix client and then pushed into the Phoenix server caches of the data table regions. Finally, on the server side, data table rows are scanned and joined with the index rows using HashJoin. Based on the selectivity of the original query, this join operation may still result in scanning a large amount of data table rows. 
Eliminating these data table scans would be a significant improvement. To do …
=> PHOENIX-6458 Using global indexes for queries with uncovered columns

pom.xml
Previous Zookeeper version was broken on JDK 14+ due to the incorrect usage of
InetSocketAddress.toString. For reference see: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8232369
=> PHOENIX-6723 Update client to use Zookeeper 3.5.7 and Curator 4.2.0

phoenix-core/src/it/java/org/apache/phoenix/end2end/PreMatureTimelyAbortScanIt.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ScanningResultIterator.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/TableResultIterator.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/TableSnapshotResultIterator.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixConnection.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/PhoenixRecordReader.java, pom.xml
Added isClosing property in PhoenixConnection as well, as we change isClose status after closing all the underline objects (Iterators, scanners, statements).
=> PHOENIX-6776 :- Abort scans of closed connections at ScanningResultIterator

phoenix-core/src/main/java/org/apache/phoenix/coprocessor/MetaDataRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexTool.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexUpgradeTool.java, phoenix-core/src/main/java/org/apache/phoenix/util/ScanUtil.java, phoenix-core/src/test/java/org/apache/phoenix/query/BaseTest.java
Reverts apache/phoenix#1566
As described in https://issues.apache.org/jira/browse/PHOENIX-6898 this change is breaking indexing tests with 2.5 profile.
I will reopen PHOENIX-6884 and working on a fix for it.
=> Revert "PHOENIX-6884 Phoenix to use hbase.rpc.read.timeout and hbase.rpc.writ…"

pom.xml
If that's too much of a jump, then we could bump instead to 2.12.7.1 :)
=> PHOENIX-6981 Update Jackson to 2.14.1

phoenix-core/src/it/java/org/apache/phoenix/end2end/DerivedTableIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/FlappingLocalIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/QueryLoggerIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/BaseLocalIndexIT.java, phoenix-core/src/main/antlr3/PhoenixSQL.g, phoenix-core/src/main/java/org/apache/phoenix/compile/ExplainPlanAttributes.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ExplainTable.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ExplainType.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ParseNodeFactory.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java
Query syntax: `EXPLAIN WITH REGIONS {query}`
Example:
Assuming the scan is prepared for 4 region locations,
When `phoenix.max.region.locations.size.explain.plan` is set as `2`, only 2 region locations are printed:
```
CLIENT PARALLEL 4-WAY RANGE SCAN OVER N000001:N000002 [1,'a'] - [1,'b']
SERVER MERGE [0.K3]
SERVER FILTER BY FIRST KEY ONLY
(region locations = [region=N000001:N000002,,1683068961616.4773aca00009beabd2316e0be5828ffa., hostname=localhost,55546,1683068927671, seqNum=9, region=N000001:N000002,e\x00\x00\x00\x00\x00\x00\x00\x00\x00,1683068961616.77243f1c70242067f53018949e146393., hostname=localhost,55546,1683068927671, seqNum=9]...total size = 4) 
CLIENT MERGE SORT
```
With default value of `phoenix.max.region.locations.size.explain.plan` as `5`, all region locations are printed: …
=> PHOENIX-6907 Explain Plan should output region locations with servers

phoenix-core/src/it/java/org/apache/phoenix/end2end/PhoenixRegionServerEndpointIT.java, phoenix-core/src/main/java/org/apache/phoenix/cache/ServerMetadataCache.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/PhoenixRegionServerEndpoint.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/VerifyLastDDLTimestamp.java, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core/src/main/java/org/apache/phoenix/exception/StaleMetadataCacheException.java, phoenix-core/src/main/java/org/apache/phoenix/util/ServerUtil.java, phoenix-core/src/main/protobuf/RegionServerEndpointService.proto, phoenix-core/src/test/java/org/apache/phoenix/cache/ServerMetadataCacheTest.java
1. Create a new region server level coproc: PhoenixRegionServerCoprocessor
2. Added a sample method to validate last DDL timestamp for list of tables.
3. Added test cases.
=> PHOENIX-6988 Create new regionserver coprocessor named PhoenixRegionServerEndpoint in Phoenix

phoenix-core/src/it/java/org/apache/phoenix/end2end/LikeExpressionIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereOptimizer.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ParallelIterators.java, phoenix-core/src/test/java/org/apache/phoenix/compile/WhereOptimizerTest.java
=> PHOENIX-6960 Scan range is incorrect when query desc columns

phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java
Added a log line for understanding Stale Region Boundary error better
=> PHOENIX-7002 : Added log line for Stale Region Boundary Cache Exception

phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core/src/test/java/org/apache/phoenix/query/ConnectionQueryServicesImplTest.java
Changing the region boundary detection conditions
=> PHOENIX-7003 Harden hbase region inconsistencies check in CQSI#getAllTableRegions method

phoenix-core/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/GlobalClientMetrics.java, phoenix-core/src/main/java/org/apache/phoenix/monitoring/MetricType.java, phoenix-core/src/main/java/org/apache/phoenix/util/ValidateLastDDLTimestampUtil.java, phoenix-core/src/test/java/org/apache/phoenix/cache/ServerMetadataCacheTest.java
On the write path, if `phoenix.ddl.timestamp.validation.enabled` is set:
- Pick a random live region server and call the `validateLastDDLTimestamp` RPC for all the tables/views in the `mutationsMap`
-  Include all indexes on the table/view in case their state had changed
-  Include all ancestors of views
-  If `StaleMetadataCacheException` is encountered, force update client side cache for all the tables/views. 
- ~~Replace the `PTable` object in all the `TableRefs` with the latest `PTable` for every table/view.~~
- `MutationState#validateAndGetServerTimestamp` should take care of this.
=> PHOENIX-7026 : Validate LAST_DDL_TIMESTAMP for write requests

bin/hbase-omid-client-config.yml
Since [Omid-247](https://github.com/apache/phoenix-omid/commit/7d3cf3e83586bc523e20277113ecb844172cefc0) has been merged, the default port has changed from 54758 to 24758. The TSO configuration in the Phoenix component also needs to be updated.
=> PHOENIX-7160 Change the TSO default port to be compatible with Omid 1.1.1

pom.xml
With the above change, we can select the integration tests which we want to run using following commands
- To run the integration tests only for ParallelStatsEnabledTests
`mvn integration-test -DskipParallelStatsDisabledTests=true -DskipNeedsOwnMiniClusterTests=true`
- To run the integration tests only for ParallelStatsDisabledTests
`mvn integration-test -DskipParallelStatsEnabledTests=true -DskipNeedsOwnMiniClusterTests=true`
- To run the integration tests only for ParallelStatsDisabledTests
`mvn integration-test -DskipParallelStatsEnabledTests=true -DskipParallelStatsDisabledTests=true`
- To run both ParallelStatsEnabledTests and ParallelStatsDisabledTests
`mvn integration-test -DskipNeedsOwnMiniClusterTests=true`
=> PHOENIX-7156 enabling category-wise integration test execution capability

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/PartialIndexIT.java
Currently in the integration test for partial index, partial index table obtained from result set is compared against expected schema and table name. But there is no test case to validate explain plan for partial index.
This PR adds query plan test case for partial index.
=> PHOENIX-7187 Improvement of Integration test case with Explain Plan for Partial Index

pom.xml
=> PHOENIX-7234 Bump org.apache.commons:commons-compress from 1.21 to 1.26.0

phoenix-core/src/it/java/org/apache/phoenix/end2end/MoveTTLDuringUpgradeIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/UpgradeIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ViewTTLIT.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryConstants.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/main/java/org/apache/phoenix/util/UpgradeUtil.java
This PR changes the TTL column data type in syscat to VARCHAR. The in-memory representation in PTable is still integer. That will change in a subsequent PR with PHOENIX-7170
=> PHOENIX-7329 Change TTL column type to VARCHAR in syscat

phoenix-core-client/src/main/java/org/apache/phoenix/schema/PTableImpl.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCQueryIT.java
Jira: PHOENIX-7348
This fixes the issue that the new table attribute that represents the CDC INCLUDES value is not part of the serialization and so client is not seeing the attribute and not using it. Added a test to make sure the default value is getting used.
=> PHOENIX-7348: Serialize the CDC_INCLUDES table attribute and add a test

phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java
Jira: PHOENIX-7363
**All meta handlers on SYSTEM.CATALOG regionserver exhausted within CQSI#init**
After allowing readLock for getTable API at the server side ([PHOENIX-6066](https://issues.apache.org/jira/browse/PHOENIX-6066)), it seems that under heavy load, all meta handler threads can get exhausted within ConnectionQueryServicesImpl initialization as part of any of the MetaDataEndpointImpl coproc operations. When the table details are not present in the cache, MetaDataEndpointImpl coproc can attempt to create new connection on the server side in order to scan SYSTEM.CATALOG. Under heavy load, several (all of) meta handlers – which are dedicated for all metadata (system table) operations – could attempt to create server side connection, which can further lead into creating new …
=> PHOENIX-7363 Protect server side metadata cache updates for the given PTable

phoenix-core-client/src/main/java/org/apache/phoenix/compile/ProjectionCompiler.java, phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/BaseScannerRegionObserverConstants.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/ExpressionType.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/function/BsonValueFunction.java, phoenix-core-client/src/main/java/org/apache/phoenix/parse/BsonValueParseNode.java, phoenix-core-server/src/main/java/org/apache/phoenix/iterate/NonAggregateRegionScannerFactory.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson4IT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/json/JsonFunctionsIT.java
Jira: PHOENIX-7396
The purpose of this Jira is to introduce new function for BSON data type to retrieve the value of the given Bson Document field key. The function should also take data type as an argument to decode the document field value.
**Name:** BSON_VALUE
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-5af8d1c2-7fff-f0d8-4b65-50f2510b6936"><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Arguments:</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
  | Expression | DataType
-- | -- …
=> PHOENIX-7396 BSON_VALUE function to retrieve BSON field value with given data type

pom.xml
Update transitive dependency of woodstox-core to 5.4.0
This dependency is a transitive dependency of hadoop, which is using a
5.3.0 version which is currently flagged with 5 CVEs.
=> PHOENIX-7393 Update transitive dependency of woodstox-core to 5.4.0

phoenix-core-server/src/main/java/org/apache/phoenix/iterate/SnapshotScanner.java, phoenix-core-server/src/main/java/org/apache/phoenix/iterate/TableSnapshotResultIterator.java
Jira: PHOENIX-7367
1. Disable mslab for region created within snapshot (by setting hbase.hregion.memstore.mslab.enabled set to false)
2. In TableSnapshotResultIterator - Remove the the SnapshotScanner's close (via ScanningResultIterator) called within next method. It would anyways be closed by the mapper at the end while closing the record reader
=> PHOENIX-7367 - Snapshot based mapreduce jobs fails after HBASE-28401

phoenix-core-server/src/main/java/org/apache/phoenix/iterate/SnapshotScanner.java
PHOENIX-7387  SnapshotScanner's next method is ignoring the boolean value from hbase's nextRaw method
The pr include the following changes
1) Now we are using the return type of hbase scanner, which is a boolean value to decide what resultset we should pass to the caller.
Tested in our local setup.
=> PHOENIX-7387: SnapshotScanner's next method is ignoring the boolean value from hbase's nextRaw method

phoenix-core-client/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core-client/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core-client/src/main/java/org/apache/phoenix/index/PhoenixIndexBuilderHelper.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixPreparedStatement.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/builder/BaseIndexBuilder.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/builder/IndexBuildManager.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/builder/IndexBuilder.java, phoenix-core-server/src/main/java/org/apache/phoenix/index/PhoenixIndexBuilder.java, phoenix-core-server/src/main/java/org/apache/phoenix/iterate/NonAggregateRegionScannerFactory.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson4IT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKey2IT.java
Jira: PHOENIX-7398
Phoenix supports Atomic Conditional Upserts with ON DUPLICATE KEY clause, allowing clients to either ignore the update if the row with the given primary key(s) already exist or conditionally update the row with the given primary key(s). Phoenix also supports returning 0 or 1 as updated status code for the given Atomic/Conditional Upserts, where 0 represents no updates to the row and 1 represents the updated row (when the condition is satisfied by the atomic upsert).
While standard JDBC APIs support Upserts with the status code returned as integer values 0 or 1, some client applications also require returning the current row state back to the client depending on whether the row is successfully updated. If the condition is satisfied by the atomic upsert and the row is …
=> PHOENIX-7398 New PhoenixStatement API to return row for Atomic/Conditional Upserts

phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/TableTTLInfo.java, phoenix-core-client/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixDatabaseMetaData.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/ConditionTTLExpression.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/DelegateTable.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/LiteralTTLExpression.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/PTable.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/PTableImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/TTLConditionExpression.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/TTLExpression.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/TTLLiteralExpression.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/TableProperty.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/ScanUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CompactionScanner.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/mapreduce/index/IndexScrutinyMapper.java, phoenix-core-server/src/main/java/org/apache/phoenix/mapreduce/util/DefaultPhoenixMultiViewListProvider.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CreateTableIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/SetPropertyIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TTLAsPhoenixTTLIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TTLIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ViewTTLIT.java, phoenix-core/src/test/java/org/apache/phoenix/schema/ConditionalTTLExpressionDDLTest.java, phoenix-core/src/test/java/org/apache/phoenix/schema/TTLExpressionTest.java, phoenix-core/src/test/java/org/apache/phoenix/util/ScanUtilTest.java, phoenix-core/src/test/java/org/apache/phoenix/util/TestUtil.java
This PR lays the framework of Conditional TTL.
1. Introduces a new abstract class to hold both conditional TTL and literal TTL values in PTable
2. Simplifies the TTLTracker interface in PhoenixCompactionScanner
3. Introduces the hooks in PhoenixCompactionScanner to work with any type of TTL expression
4. Basic DDL checks in Create/Alter table for Conditional TTL
Tests ran locally:
ViewTTLIT, TTLAsPhoenixTTLIT, TableTTLIT
=> PHOENIX-7383 Unify in-memory representation of Conditional TTL expressions and Literal TTL values

phoenix-core-client/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKey2IT.java
Jira: PHOENIX-7411
PHOENIX-7398 introduces new PhoenixStatement API to return row for Atomic/Conditional Upserts. Phoenix already supports Upserts as Atomic operation by using ON DUPLICATE KEY clause. However, Deletes are not supported as atomic and single Delete query can also delete multiple rows based on the WHERE clause used.
HBase does not provide API to return row state for atomic updates with Put and Delete mutations. HBase API checkAndMutate() also supports returning Result for Append and Increment mutations only, not for Put and Delete mutations.
The purpose of this Jira is to introduce support for atomic delete of single row that can return the row only if it existed before executing the Delete mutation. If the row is already deleted, the API support is not expected to return …
=> PHOENIX-7411 Atomic Delete: PhoenixStatement API to return row if single row is atomically deleted

phoenix-core/src/it/java/org/apache/phoenix/end2end/TableTTLIT.java
When multiple updates happen to the same row within the same millisecond the latest update simply overwrites the cells of the previous update. This breaks the test.
=> PHOENIX-7422 Fix Flapper TableTTLIT#testMinorCompactionShouldNotRetainCellsWhenMaxLookbackIsDisabled

phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java
Jira: PHOENIX-7432
We have seen large GC spikes when some views under the same table -> view hierarchy get dropped concurrently. Upon analyzing in detail (@jpisaac's heap dump analysis), we found that multiple drop view threads are busy scanning the same table row for PHYSICAL_TABLE link. This recursive getTable is introduced by PHOENIX-6247 logical-physical table separation. We have also fixed a bug that has caused all active handlers on SYSTEM.CATALOG regionserver to get occupied due to recursive getTable call for view index table that does not exist in SYSTEM.CATALOG, we have fixed it with PHOENIX-7369.
However, with the current analysis, it is clear that getTable is trying to scan large row for the given table (family name for the PHYSICAL_TABLE link). Specifically, multiple threads …
=> PHOENIX-7432 getTable for PHYSICAL_TABLE link should use common utility

phoenix-core/src/it/java/org/apache/phoenix/end2end/TableSnapshotReadsMapReduceIT.java
This makes sure that we order both the mapreduce and direct query results when comparing them
=> PHOENIX-7440 TableSnapshotReadsMapReduceIT fails with HBase 2.6.1

phoenix-core-client/src/main/java/org/apache/phoenix/schema/tool/SchemaExtractionProcessor.java, phoenix-core/src/it/java/org/apache/phoenix/schema/tool/SchemaToolExtractionIT.java
A column which is a PK column was incorrectly classified as non PK column and calling `col.getFamilyName().getString()` will cause NPE because familyName is null for PK columns
=> PHOENIX-7468 NPE in SchemaExtractionTool on salted table

phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CDCGlobalIndexRegionScanner.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/UncoveredIndexRegionScanner.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java
For regular indexes we do index maintenance such that if a data table row is deleted, we also delete the corresponding index row. This is especially needed for covered indexes for correctness as we use the index alone to serve the queries.
For uncovered indexes, this delete is not necessary for correctness but needed for performance reason not to scan deleted rows again and again, and not to attempt to scan the corresponding deleted data table rows. However, none of these reasons are really applicable to CDC indexes. Since CDC index table rows expires quickly we do not really need to delete them. It is also expected that a CDC index row is scanned once.
For CDC indexes we add an extra delete markers for each deleted row to have two delete markers, one with the embedded row timestamp value …
=> PHOENIX-7473 Eliminating index maintenance for CDC index

phoenix-core-client/src/main/java/org/apache/phoenix/util/ViewUtil.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ViewUtilIT.java
Adding utilitiy method to get view index ids for given view index table
JIRA - [PHOENIX-7304](https://issues.apache.org/jira/browse/PHOENIX-7304)
=> PHOENIX-7304 - Adding utilitiy method to get view index ids for given view index table

phoenix-core-client/src/main/java/org/apache/phoenix/compile/DeleteCompiler.java, phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/BaseScannerRegionObserverConstants.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/UngroupedAggregateRegionObserver.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/UngroupedAggregateRegionScanner.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKey2IT.java
Jira: PHOENIX-7434
PHOENIX-7411 introduces Atomic Delete support for the single row deletion. It returns result (row) back to the client (using new API) only if the given client initiated Delete operation deleted the row when the row was alive. In the context of atomicity, this means that the delete operation is already idempotent and will continue to be idempotent, however only the client that was able to successfully delete the row by taking lock on the live row (row without delete marker) is the only one that can return the old row result back.
PHOENIX-7411 support includes only single row if the WHERE clause contains only pk columns as single row point lookup plan. However, user can also add additional non-pk columns in the WHERE clause in addition to all pk columns, this also makes …
=> PHOENIX-7434 Extend atomic support to single row delete with condition on non-pk columns

pom.xml
Remove `repository.apache.org` definition, to let the build use `central` repo from super POM.
Please see last item about `repository.apache.org` at https://infra.apache.org/infra-ban.html.
https://issues.apache.org/jira/browse/PHOENIX-7488
Local build:
```
$ mvn -DskipTests clean package
...
[INFO] Reactor Summary for Apache Phoenix 5.3.0-SNAPSHOT:
[INFO] 
[INFO] Apache Phoenix ..................................... SUCCESS [  0.988 s]
[INFO] Phoenix Hbase 2.6.0 compatibility .................. SUCCESS [ 15.988 s]
[INFO] Phoenix Hbase 2.5.4 compatibility .................. SUCCESS [ 15.753 s]
[INFO] Phoenix Hbase 2.5.0 compatibility .................. SUCCESS [ 26.659 s]
[INFO] Phoenix Hbase 2.4.1 compatibility .................. SUCCESS [ 17.087 s]
[INFO] Phoenix Core Client …
```
=> PHOENIX-7488. Use central repo, not repository.apache.org

phoenix-core-client/src/main/java/org/apache/phoenix/compile/JoinCompiler.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MixedCaseInnerJoinAliasesIT.java
-Fixed issue in JoinCompiler, by escaping already normalised alias ( and preventing it from incorrectly getting converted to UPPERCASE).
-Added Unit test.
=> PHOENIX-7491 Mixed-cased alias doesn't work in select statement of INNER JOIN

phoenix-core-client/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryConstants.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/PTable.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/CDCUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/TaskRegionObserver.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/tasks/CdcStreamPartitionMetadataTask.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCBaseIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCDefinitionIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCStreamIT.java
=> PHOENIX-7459 : Bootstrap stream metadata when CDC is enabled on a table

bin/performance.py, bin/pherf-standalone.py, bin/phoenix_utils.py, bin/psql.py, bin/sqlline.py, phoenix-assembly/src/build/components/all-common-dependencies.xml, phoenix-core-client/pom.xml, phoenix-core/pom.xml, phoenix-pherf/pom.xml, pom.xml
and add org.slf4g:jul-to-slf4j to classpath where needed
=> PHOENIX-7477 Set java.util.logging.config.class in scripts

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixPrefetchedResultSet.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixPreparedStatement.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixResultSet.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/TupleUtil.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson4IT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKey2IT.java
[PHOENIX-7398](https://issues.apache.org/jira/browse/PHOENIX-7398) introduces new PhoenixStatement API to return row for Atomic/Conditional Upserts. Phoenix already supports Upserts as Atomic operation by using ON DUPLICATE KEY clause.
Similarly, [PHOENIX-7411](https://issues.apache.org/jira/browse/PHOENIX-7411) and [PHOENIX-7434](https://issues.apache.org/jira/browse/PHOENIX-7434) introduce Atomic Delete support for the single row deletion. It returns result (row) back to the client (using new API) only if the given client initiated Delete operation deleted the row when the row was alive. In the context of atomicity, this means that the delete operation is already idempotent and will continue to be idempotent, however the client that was able to successfully delete the row by taking lock …
=> PHOENIX-7462 Single row Atomic Upsert/Delete returning result should return ResultSet

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/FailoverPhoenixConnection.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/FailoverPhoenixContext.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/HAURLInfo.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/HighAvailabilityGroup.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/HighAvailabilityPolicy.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/ParallelPhoenixConnection.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/ParallelPhoenixContext.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixEmbeddedDriver.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/FailoverPhoenixConnectionIT.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/HighAvailabilityGroupIT.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/HighAvailabilityGroupTestIT.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/HighAvailabilityTestingUtility.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/ParallelPhoenixConnectionIT.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/FailoverPhoenixConnectionTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixConnectionFailureTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixConnectionTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixContextTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixNullComparingResultSetTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixPreparedStatementTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixResultSetTest.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/ParallelPhoenixUtilTest.java
- Decoupling principal from HAGroupInfo so that we can have 1:1 mapping between HAGroupInfo -> HighAvailabilityGroup and 1:n mapping between HAGroupInfo -> HAURLInfo (principal)
- Storing HAURLInfo in connection's own context so it has correct info.
- Policy can access all users associated with given HAGroup in case of clusterRoleRecord change
- This means we can have a single HighAvailability group/ clusterRoleRecord for different principals connecting to it and we don't have to create separate watchers for every principal.
=> PHOENIX-7502 :- Decouple principal from HAGroupInfo

phoenix-core-client/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core-client/src/main/java/org/apache/phoenix/monitoring/MetricType.java, phoenix-core-client/src/main/java/org/apache/phoenix/monitoring/MutationMetricQueue.java, phoenix-core-client/src/main/java/org/apache/phoenix/monitoring/TableClientMetrics.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/BasePhoenixMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixTableLevelMetricsIT.java, phoenix-core/src/test/java/org/apache/phoenix/monitoring/TableMetricsManagerTest.java
Summary of the changes:
- Added a metric to track no. of mutation batches successful per commit call.
=> PHOENIX-7515: Add metric for count of Phoenix client batches used by a commit call

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/ConnectionInfo.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/RPCConnectionInfo.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/ZKConnectionInfo.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/PhoenixEmbeddedDriverTest.java
Jira: PHOENIX-7533
Before PHOENIX-6523, ConnectionInfo used to provide hbase.zookeeper.quorum with Zookeeper host names separated by comma. With PHOENIX-6523, for zk registry, ConnectionInfo provides hbase.client.zookeeper.quorum with Zookeeper hosts and port values combined, separated by comma (e.g. "host1:1234,host2:2181,host3:9876" etc).
For the purpose of creating HBase Connection, providing "hbase.client.zookeeper.quorum" is sufficient. However, Phoenix downstream applications that are using "hbase.zookeeper.quorum" value to determine which HTable threadpool to use for the given Connection can no longer function for cases like dual client where different HTable threadpools need to be used for different HBase connections.
Given that Phoenix 5.1 client used to provide …
=> PHOENIX-7533 Fix broken compatibility for Zookeeper based ConnectionInfo

phoenix-core-client/src/main/java/org/apache/phoenix/compile/CreateTableCompiler.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/ViewUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/mapreduce/transform/PhoenixTransformWithViewsInputFormat.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/BaseRowKeyMatcherTestIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ViewMetadataIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ViewUtilIT.java
=> PHOENIX-7376 : ViewUtil#findAllDescendantViews should provide two versions to differentiate CQSI initiated by clients and servers

phoenix-core-client/src/main/java/org/apache/phoenix/index/IndexMaintainer.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/IndexUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/GlobalIndexRegionScanner.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core-server/src/main/java/org/apache/phoenix/index/GlobalIndexChecker.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexToolIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/GlobalIndexCheckerIT.java, phoenix-core/src/test/java/org/apache/phoenix/index/IndexMaintainerTest.java
Add DeleteColumn cells to index rows when a column is set to null in an upsert statement.
=> PHOENIX-7543 Wrong result returned when query is served by index and some columns are null

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/ConnectionInfo.java, phoenix-core/src/test/java/org/apache/phoenix/jdbc/PhoenixEmbeddedDriverTest.java
ZK supports using square brackets around the IP address to resolve the colon ambiguity.
Added support for the square bracket notation.
(We still need to escape the colon separating the port from the address.)
i.e. accept:
"phoenix+zk:[fe:80::01]\:2181::/hbase"
=> PHOENIX-7186 Support Square Brackets Notation for IPv6 in JDBC URL

phoenix-core-client/src/main/java/org/apache/phoenix/compile/ScanRanges.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/salted/SaltedTableWithParallelStatsEnabledIT.java, phoenix-core/src/test/java/org/apache/phoenix/query/BaseTest.java
Summary of the fix:
- Without the fix `SaltedTableWithParallelStatsEnabledIT#testRangeScanForPhoenix7580WithoutStatsForParallelization()` will fail. 
- Also added the ITs to cover all the cases of different types of Phoenix level scans over a table: Point lookups, range scans and full table scan. For all the three types of scans, added tests for: using stats for parallelization vs not using stats for parallelization.
- As local indexes are not salted so, we don't need explicitly test for them.
=> PHOENIX-7580: Data in last salt bucket is not being scanned for range scan

phoenix-core-client/src/main/java/org/apache/phoenix/query/HTableFactory.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MappingTableDataTypeIT.java
We use Connection.getTable in org.apache.phoenix.query.HTableFactory. There are 2 flavors of this getTable method and the issue comes from the implementation of this method.
getTable(tableName) -> This one has a default implementation which calls getTable(tableName, null) The null here is executorService.
But in org.apache.hadoop.hbase.client.ConnectionImplementation implementation of getTable(tableName) it calls getTable(tableName, getBatchPool()) . This pool is managed by hbase code and it cleans up the pool on close() -> [link](https://github.com/enis/hbase-sal/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java#L171-L176)
Note that in existing implementation of this change we were calling HTable.close() which was closing the threadpool managed by HTable. …
=> PHOENIX-7605 Addendum Fixing IT where table was used after t.close(), passing pool to hbase client based on value.

phoenix-core-client/src/main/java/org/apache/phoenix/expression/CoerceExpression.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson4IT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CastAndCoerceIT.java
Jira: PHOENIX-7610
For the range scan or point lookup on the single row, it is required to provide either full pk columns with equal comparison (point lookup) or prefix pk columns with equal comparison operator (range scan).
However, when we use SQL CAST() function on pk columns to convert the type of the given column into another data type, the plan generated by where optimizer always performs full table scan instead of range scan or point lookup.
=> PHOENIX-7610 Using CAST() on pk columns always result in full table scan

phoenix-core-client/src/main/java/org/apache/phoenix/schema/CompiledConditionalTTLExpression.java, phoenix-core/src/it/java/org/apache/phoenix/schema/ConditionalTTLExpressionIT.java
NPE when the row key had a column with a null value and that column was part of a conditional TTL expression.
=> PHOENIX-7616 NPE when there are Conditional expressions on indexed columns

.gitignore, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixParameterMetaData.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TestUpsertBindNullParamToCaseExprIT.java
When a NULL is bound to a parameter that is inside a CASE expression of an UPSERT statement, an NPE is being generated in both client side and server side. This patch adds a null check in both places and adds a few tests. The tests that actully fail without the fix are:
- testBindWithComplexCasePHOENIX_7615
- testBindNullOnDuplicateKeyIsNull
- testBindNullOnDuplicateKeyIsNotNull2
Others were added to confirm that there is no issue and have been left to prevent regression.
=> PHOENIX-7615: Fix NPE in handling NULL value

phoenix-core-client/src/main/java/org/apache/phoenix/hbase/index/util/IndexManagementUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexToolIT.java
Added a new phase which tracks if we were able to acquire the row locks or not and accordingly decrement the reference count in pending rows.
=> PHOENIX-7591 Concurrent updates to tables with indexes can cause data inconsistency

phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/pom.xml, phoenix-core/src/it/java/org/apache/phoenix/end2end/PreStoreScannerOpenIT.java, pom.xml
Using ByteBuddy's runtime byte-code manipulation in IT to count the `StoreFileScanner#seek()` and `StoreFileScanner#reseek()` calls done for a table. HBase code already uses ByteBuddy indirectly via Mockito and is using the same version that I am adding. We can't use Mockito here as it is not able to mock/spy `StoreFileScanner` instances in mini-cluster as they are created in a separate thread different from main client thread. Thus, using ByteBuddy directly.
=> PHOENIX-7619 Excess HFiles are being read to look for more than required column versions

phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/metrics/MetricsPhoenixCoprocessorSourceFactory.java, phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/metrics/MetricsPhoenixMasterSource.java, phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/metrics/MetricsPhoenixMasterSourceImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/ParentPartitionNotFound.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/PhoenixMasterObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCBaseIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCStream2IT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCStreamIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TestPhoenixMasterObserver.java
Jira: PHOENIX-7639
If the cluster is upgraded to Phoenix 5.3 without metadata upgrade, new system tables SYSTEM.CDC_STREAM_STATUS and SYSTEM.CDC_STREAM will not be created yet.
Any region merges or splits with PhoenixMasterObserver coproc hooks can encounter errors as without the system tables, we cannot persist stream partition metadata related to region splits and merges. We need to handle this error.
Moreover, it is important to not miss the updates to SYSTEM.CDC_STREAM table as part of postCompletedSplitRegionAction() and postCompletedMergeRegionsAction(). The purpose of this Jira is to introduce maximum retries possible to make the upserts successful.
=> PHOENIX-7639 Improve error handling in PhoenixMasterObserver

phoenix-core-client/src/main/java/org/apache/phoenix/compile/DeleteCompiler.java, phoenix-core-client/src/main/java/org/apache/phoenix/execute/MutationState.java, phoenix-core-client/src/main/java/org/apache/phoenix/index/PhoenixIndexBuilderHelper.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixPreparedStatement.java, phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core-server/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java, phoenix-core-server/src/main/java/org/apache/phoenix/index/PhoenixIndexBuilder.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson4IT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/OnDuplicateKey2IT.java
Jira: PHOENIX-7646
PHOENIX-7462, PHOENIX-7398, PHOENIX-7434, PHOENIX-7411 and PHOENIX-7630 Jiras have introduced support for PhoenixStatement to return ResultSet for updated new row version.
The purpose of this PR is to add support for returning the old row state (before update) in atomic update operations. This enhancement allows applications to retrieve the previous state of a row when performing conditional updates, enabling better audit trails.
New API signature:
```
/**
* Executes the given SQL statement similar to JDBC API executeUpdate() but also returns the
* old row (before update) as Result object back to the client. This must be used with
* auto-commit Connection. This makes the operation atomic.
* If the row is successfully updated, return the old row (state before update), …
```
=> PHOENIX-7646 New PhoenixStatement API to return old row state in Atomic Updates

phoenix-core-client/src/main/java/org/apache/phoenix/expression/function/BsonValueFunction.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson6IT.java
Jira: PHOENIX-7650
BSON_VALUE() helps retrieve the value of any document field key with all the corresponding data types. For instance, if the value of the given document field is of type BsonString and BSON_VALUE() specifies VARCHAR as data type for parsing the value at the client side, BsonString value will be encoded to VARCHAR data type and returned back as the function output with PVarchar type.
The purpose of this PR is to introduce default value support for all of the supported scalar data types. This can help avoid multiple calls to BSON_VALUE() function. For instance, let's consider all the rows of the table has BsonDocument which might contain TTL field. The query that needs to retrieve the value of TTL can be something similar to
`WHERE BSON_VALUE(COL, 'ttlField', 'BIGINT') IS …
=> PHOENIX-7650 Default value support in BSON_VALUE() for all supported types

phoenix-core-client/src/main/antlr3/PhoenixBsonExpression.g, phoenix-core-client/src/main/java/org/apache/phoenix/expression/util/bson/BsonConditionInvalidArgumentException.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/util/bson/SQLComparisonExpressionUtils.java, phoenix-core-client/src/main/java/org/apache/phoenix/parse/DocumentFieldBeginsWithParseNode.java, phoenix-core-client/src/main/java/org/apache/phoenix/parse/ParseNodeFactory.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson1IT.java, phoenix-core/src/test/java/org/apache/phoenix/util/bson/ComparisonExpressionUtilsTest.java
Jira: PHOENIX-7585
PHOENIX-7463 provides us with the ability to generate and evaluate AST (Abstract Syntax Tree) for the BSON condition expression evaluation for it's SQL type expressions.
The purpose of this PR is to provide a new internal function (similar to field_exists(), field_not_exists() etc) within BSON_CONDITION_EXPRESSION() such that it can identify whether the value of the given document field of type BsonString or BsonBinary has prefix value as the constant provided in the second argument.
begins_with(fieldKey, substr) => here, fieldKey represents path in the given BSON document. substr represents value which needs to be compared as the prefix value of path field from the document. The function should only support BsonString and BsonBinary types for prefix search.
=> PHOENIX-7585 New BSON Condition Function begins_with()

phoenix-core-client/src/main/antlr3/PhoenixBsonExpression.g, phoenix-core-client/src/main/java/org/apache/phoenix/expression/util/bson/CommonComparisonExpressionUtils.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/util/bson/SQLComparisonExpressionUtils.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/util/bson/UpdateExpressionUtils.java, phoenix-core-client/src/main/java/org/apache/phoenix/parse/DocumentFieldContainsParseNode.java, phoenix-core-client/src/main/java/org/apache/phoenix/parse/ParseNodeFactory.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson1IT.java, phoenix-core/src/test/java/org/apache/phoenix/util/bson/ComparisonExpressionUtilsTest.java
Jira: PHOENIX-7662
PHOENIX-7463 provides us with the ability to generate and evaluate AST (Abstract Syntax Tree) for the BSON condition expression evaluation for it's SQL type expressions.
The purpose of this Jira is to provide a new internal function for BSON_CONDITION_EXPRESSION() to help evaluate whether value of the given field key contains a particular value.
contains(fieldKey, val) => here, fieldKey represents field key's path in the given BSON document. val represents value which needs to be compared.
The function evaluation returns true if the value of the field contains the specified value. The field can be:
- A string that contains a particular substring
- A set that contains a particular element within the set
- A list that contains a particular element within the list
=> PHOENIX-7662 BSON Condition Function contains()

phoenix-core-client/src/main/java/org/apache/phoenix/util/CDCChangeBuilder.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CDCCompactionUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CDCGlobalIndexRegionScanner.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson3IT.java, phoenix-core/src/it/java/org/apache/phoenix/schema/ConditionalTTLExpressionIT.java
Jira: PHOENIX-7658
As a follow-up to PHOENIX-7653 which introduced TTL_DELETE as new CDC event type, we should not return pre-built pre-image with CDC JSON if the SELECT query does not have PRE scope.
=> PHOENIX-7658 CDC event for TTL_DELETE to exclude pre-image if PRE scope is not selected

phoenix-core-client/src/main/java/org/apache/phoenix/util/ScanUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson3IT.java, phoenix-core/src/it/java/org/apache/phoenix/schema/ConditionalTTLExpressionIT.java
Jira: PHOENIX-7664
CDC Scanners like other Global index scanners attempt to remove EmptyColumnOnlyFilter and FirstKeyOnlyFilter from the scan, however it is not enough when EmptyColumnOnlyFilter or FirstKeyOnlyFilter is used with other filters e.g. PageFilter with LIMIT.
For CDC queries, the user initiated upsert and delete statements do not face any issues as the scan on the uncovered index is only expected to retrieve empty column cell. However, it does not work when we need to retrieve more cells than just empty column e.g. `_CDC_IMG_` column cell should be returned by the delegate scanner for TTL expired CDC events.
The purpose of this PR is to remove the filters even when they are used in combination with others.
=> PHOENIX-7664 Remove EmptyColumnOnlyFilter and FirstKeyOnlyFilter for CDC scanners

phoenix-core-server/src/main/java/org/apache/phoenix/replication/metrics/MetricsReplicationLogProcessor.java, phoenix-core-server/src/main/java/org/apache/phoenix/replication/metrics/MetricsReplicationLogProcessorImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/replication/metrics/ReplicationLogProcessorMetricValues.java, phoenix-core-server/src/main/java/org/apache/phoenix/replication/reader/ReplicationLogProcessor.java, phoenix-core-server/src/main/java/org/apache/phoenix/replication/reader/package-info.java, phoenix-core/src/test/java/org/apache/phoenix/replication/reader/ReplicationLogProcessorTest.java
JIRA - [PHOENIX-7632](https://issues.apache.org/jira/browse/PHOENIX-7632)
Adding the ReplicationLogProcessor component, that accepts a single replication log file, process mutations in configurable batch size and apply them to HBase table via async client.
The Replication Log Discovery (to be added as part of [PHOENIX-7568](https://issues.apache.org/jira/browse/PHOENIX-7568)) would list the log files and use ReplicationLogProcessor to read and apply the mutations to respective HBase table.
The Discovery and Tracking (Marking file in-progrss / deletion after successful processing) will be done as part of [PHOENIX-7568](https://issues.apache.org/jira/browse/PHOENIX-7568).
=> Phoenix-7632 Adding ReplicationLogProcessor Component

phoenix-core-client/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCStreamIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/PropertiesInSyncIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TableTTLIT.java, phoenix-core/src/it/java/org/apache/phoenix/schema/ConditionalTTLExpressionIT.java
Co-authored-by: Palash Chauhan <palashc983@gmail.com>
Jira: PHOENIX-7671
TTL of the CDC index is same as the maxLookback configured at the cluster level. If the data table has different value of maxLookback than cluster level, the table level maxLookback is not used as TTL by the cdc index of the same data table.
The purpose of this PR is to sync the value of maxLookback from data table to index table's TableDescriptor while creating the index. Similarly, when the maxLookback value of the data table is altered using ALTER TABLE DDL, same value should be applied to all indexes.
The major compaction of CDC index should therefore consider data table's maxLookback value (from data table's descriptor) as it's TTL value.
=> PHOENIX-7671 Sync maxLookback from data table to indexes

phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CDCCompactionUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CompactionScanner.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TableTTLIT.java, phoenix-core/src/it/java/org/apache/phoenix/schema/ConditionalTTLExpressionIT.java, phoenix-core/src/test/java/org/apache/phoenix/util/TestUtil.java
Jira: PHOENIX-7677
Inserting TTL_DELETE CDC event from CompactionScanner for single expired row at a time can cause slight degradation to the write workload to the CDC index table.
To improve the performance of inserting TTL_DELETE events, CompactionScanner can accumulate 50 mutations by default and perform the batchMutate(). Any mutations that are not inserted into the CDC index should be inserted with batchMutate() while closing the CompactionScanner.
=> PHOENIX-7677 TTL_DELETE CDC event to use batch mutation
