apache/phoenix

phoenix-queryserver/src/main/java/org/apache/phoenix/queryserver/server/AvaticaServerConfigurationFactory.java, phoenix-queryserver/src/test/java/org/apache/phoenix/queryserver/server/CustomAvaticaServerConfigurationTest.java
@gjacoby126 Quick Review Please?
=> PHOENIX-4894 Missing Apache license in two QueryServer classes

phoenix-core/src/it/java/org/apache/phoenix/schema/stats/BaseStatsCollectorIT.java, phoenix-core/src/main/java/org/apache/phoenix/query/GuidePostsCache.java, phoenix-core/src/main/java/org/apache/phoenix/schema/stats/StatisticsUtil.java, phoenix-core/src/main/java/org/apache/phoenix/schema/stats/UpdateStatisticsTool.java, phoenix-core/src/test/java/org/apache/phoenix/schema/stats/UpdateStatisticsToolTest.java
@dbwong @BinShi-SecularBird Please review.
=> PHOENIX-5091 Add new features to UpdateStatisticsTool

phoenix-core/src/main/java/org/apache/phoenix/compile/ScanRanges.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/test/java/org/apache/phoenix/compile/ScanRangesIntersectTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/KeyRangeMoreTest.java
Add the utility functions from my local work that @BinShi-SecularBird needed access to.
=> Phoenix stats Initial Commit

phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java
=> PHOENIX-5408: Typo in ConnectionQueryServicesImpl Warning Logging

bin/phoenix_utils.py
Update to use existing pattern in the utility class.
=> PHOENIX-5444 Incorrect Phoenix Client Path in phoenix_utils.py

phoenix-core/src/it/java/org/apache/phoenix/end2end/MetaDataEndpointImplIT.java
make declared package consistent with directory
=> PHOENIX-5471 MetaDataEndpointImplIT declares wrong package

pom.xml
remove bouncycastle references from pom
=> PHOENIX-5549 BouncyCastle dependency definition has no effect

phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexExtendedIT.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexTool.java
PHOENIX-5512 IndexTool to set a disabled index to active
=> PHOENIX-5512 Indextool should set disabled index to active

phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexToolIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/IndexVerificationOutputRepositoryIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/IndexVerificationResultRepositoryIT.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/IndexRebuildRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/IndexToolVerificationResult.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexTool.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexVerificationOutputRepository.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexVerificationOutputRow.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexVerificationResultRepository.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/PhoenixIndexImportDirectReducer.java, phoenix-core/src/main/java/org/apache/phoenix/util/ByteUtil.java
=> PHOENIX-5799 - Inline Index Verification Output API

phoenix-core/src/it/java/org/apache/phoenix/end2end/ParameterizedIndexUpgradeToolIT.java
Note to reviewers:
I'll be unavailable until Jun 28, so if you +1 it, please commit it as well, if you can.
=> PHOENIX-5968 Undeclared org.apache.commons.lang dependency

phoenix-core/src/it/java/org/apache/phoenix/end2end/InListIT.java
These changes have reduced the time of the test from 16mins to 50seconds.
=> PHOENIX-6034 Optimize InListIT

phoenix-core/src/main/java/org/apache/phoenix/compile/CreateTableCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/GlobalIndexRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexTool.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/index/IndexVerificationResultRepository.java, phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/util/IndexUtil.java
=> PHOENIX-6263 : Close Table resources for certain workflows

phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java
* Fix SystemTablesCreationOnConnectionIT.testUpgradeNotAllowed() failure caused by internally using read-only ImmutableHTableDescriptor to set coproc SystemCatalogRegionObserver
=> PHOENIX-6270 : Use TableDescriptorBuilder to set coproc SystemCatalogRegionObserver and avoid using ImmutableHTableDescriptor

phoenix-core/src/it/java/org/apache/phoenix/end2end/UpgradeIT.java
=> PHOENIX-6284 : De-flake UpgradeIT#testConcurrentUpgradeThrowsUpgradeInProgressException

phoenix-core/src/it/java/org/apache/phoenix/end2end/UpsertSelectIT.java
=> PHOENIX-6289 : De-flake UpsertSelectIT#testUpsertSelectWithNoIndex

phoenix-core/src/it/java/org/apache/phoenix/end2end/index/LocalIndexIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ProjectionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RegionScannerFactory.java
=> PHOENIX-6421 Selecting an indexed array value from an uncovered column with local index returns NULL.

phoenix-pherf/src/main/java/org/apache/phoenix/pherf/Pherf.java, phoenix-pherf/src/test/java/org/apache/phoenix/pherf/PherfTest.java
=> PHOENIX-6554 Pherf CLI option long/short option names do not follow conventions

phoenix-pherf/src/main/java/org/apache/phoenix/pherf/workload/mt/generators/UniformDistributionLoadEventGenerator.java
changed UniformDistributionLoadEventGenerator. added numTenants attribute for generating the tenant id.
=> PHOENIX-6530 - changed the tenant id generation for uniform distribution load generator

phoenix-core/src/it/java/org/apache/phoenix/end2end/InListIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereOptimizer.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java
This reverts commit 04e79487d44c77a5ba9da6918f189c2bab94a2b8.
=> Revert "PHOENIX-6751 Force using range scan vs skip scan when using large IN clause"

phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixMetricsIT.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixConnection.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixDriver.java
[PHOENIX-6779](https://issues.apache.org/jira/browse/PHOENIX-6779) Account for connection attempted & failure metrics in all paths
=> PHOENIX-6779 Account for connection attempted & failure metrics in all paths

phoenix-core/src/it/java/org/apache/phoenix/end2end/RowValueConstructorIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/SkipScanQueryIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereOptimizer.java
Signed-off-by: Gokcen Iskender <gokceng@gmail.com>
=> PHOENIX-6659 RVC query fix for variable column + fixed column

phoenix-core/src/it/java/org/apache/phoenix/end2end/SkipScanQueryIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereOptimizer.java, phoenix-core/src/main/java/org/apache/phoenix/query/KeyRange.java
Signed-off-by: Gokcen Iskender <gokceng@gmail.com>
=> PHOENIX-6662 Failed to delete when PK with DESC with IN clause

phoenix-core/src/it/java/org/apache/phoenix/end2end/LikeExpressionIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/WhereOptimizer.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ParallelIterators.java, phoenix-core/src/test/java/org/apache/phoenix/compile/WhereOptimizerTest.java
=> PHOENIX-6960 Scan range is incorrect when query desc columns

phoenix-core/src/main/java/org/apache/phoenix/compile/DeleteCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ServerBuildIndexCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ServerBuildTransformingTableCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/UpsertCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/GlobalIndexRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/IndexerRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/MetaDataRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/UngroupedAggregateRegionScanner.java, phoenix-core/src/main/java/org/apache/phoenix/index/GlobalIndexChecker.java, phoenix-core/src/main/java/org/apache/phoenix/index/IndexMetaDataCacheClient.java, phoenix-core/src/main/java/org/apache/phoenix/index/PhoenixIndexCodec.java, phoenix-core/src/main/java/org/apache/phoenix/mapreduce/PhoenixServerBuildIndexInputFormat.java, phoenix-core/src/main/java/org/apache/phoenix/util/ScanUtil.java
=> PHOENIX-7028 Annotate client initiated Scan with metadata attributes

phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCMiscIT.java, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionInfo.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/main/java/org/apache/phoenix/schema/PTableImpl.java, phoenix-core/src/main/java/org/apache/phoenix/schema/TableProperty.java, phoenix-core/src/main/protobuf/PTable.proto
Follow up PR for #1681
Jira: [PHOENIX-7008](https://issues.apache.org/jira/browse/PHOENIX-7008)
=> PHOENIX-7008 Tweaks, fixes and additional test coverage for CREATE CDC

phoenix-core/src/it/java/org/apache/phoenix/end2end/ConnectionQueryServicesTestImpl.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/LoggingConnectionLimiterIT.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/LoggingHAConnectionLimiterIT.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/LoggingSingleConnectionLimiterIT.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixConnection.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixMonitoredConnection.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/log/ActivityLogInfo.java, phoenix-core/src/main/java/org/apache/phoenix/log/BaseConnectionLimiter.java, phoenix-core/src/main/java/org/apache/phoenix/log/ConnectionActivityLogger.java, phoenix-core/src/main/java/org/apache/phoenix/log/ConnectionLimiter.java, phoenix-core/src/main/java/org/apache/phoenix/log/DefaultConnectionLimiter.java, phoenix-core/src/main/java/org/apache/phoenix/log/LoggingConnectionLimiter.java, phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core/src/main/java/org/apache/phoenix/query/DelegateConnectionQueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java
=> PHOENIX-7063 Track and account garbage collected phoenix connections

phoenix-core/src/it/java/org/apache/phoenix/end2end/json/JsonFunctionsIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ExpressionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/UpsertCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/expression/ExpressionType.java, phoenix-core/src/main/java/org/apache/phoenix/expression/function/DistinctCountAggregateFunction.java, phoenix-core/src/main/java/org/apache/phoenix/expression/function/JsonQueryFunction.java, phoenix-core/src/main/java/org/apache/phoenix/parse/JsonModifyParseNode.java, phoenix-core/src/main/java/org/apache/phoenix/parse/JsonQueryParseNode.java, phoenix-core/src/main/java/org/apache/phoenix/parse/SelectStatement.java, phoenix-core/src/main/java/org/apache/phoenix/util/json/BsonDataFormat.java
Added JsonQueryFunction support.
A minor refactoring to keep each of the functions into their respective ParseNodes
=> PHOENIX-7058 : Implement json_query function on the json object

phoenix-core/src/it/java/org/apache/phoenix/end2end/BaseMutationBatchFailedStateMetricIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MutationBatchFailedStateMetricWithAllDeleteIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MutationBatchFailedStateMetricWithAllUpsertIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MutationBatchFailedStateMetricWithDeleteAndUpsertIT.java, phoenix-core/src/it/java/org/apache/phoenix/execute/PartialCommitIT.java, phoenix-core/src/main/java/org/apache/phoenix/execute/MutationState.java
JIRA :- [PHOENIX-5980](https://issues.apache.org/jira/browse/PHOENIX-5980)
=> PHOENIX-5980 : MUTATION_BATCH_FAILED_SIZE metric is incorrectly updated for failing delete mutations

phoenix-core/src/it/java/org/apache/phoenix/end2end/json/JsonFunctionsIT.java, phoenix-core/src/it/resources/json/json_datatypes.json, phoenix-core/src/it/resources/json/json_functions_basic.json, phoenix-core/src/it/resources/json/json_functions_tests.json, phoenix-core/src/main/java/org/apache/phoenix/compile/ExpressionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ProjectionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MetaDataClient.java
[PHOENIX-7044](https://issues.apache.org/jira/browse/PHOENIX-7044)
=> PHOENIX-7044 : Support Index on a generated column that extracts a scalar value from JSON column

phoenix-core/src/it/java/org/apache/phoenix/end2end/json/JsonFunctionsIT.java, phoenix-core/src/it/resources/json/json_functions_basic.json, phoenix-core/src/main/java/org/apache/phoenix/expression/ExpressionType.java, phoenix-core/src/main/java/org/apache/phoenix/expression/function/JsonExistsFunction.java, phoenix-core/src/main/java/org/apache/phoenix/parse/JsonExistsParseNode.java, phoenix-core/src/main/java/org/apache/phoenix/util/json/BsonDataFormat.java, phoenix-core/src/main/java/org/apache/phoenix/util/json/BsonJsonProvider.java, phoenix-core/src/main/java/org/apache/phoenix/util/json/JsonDataFormat.java
JSON_EXISTS determines whether a JSON value satisfies a search criterion.
SELECT Col1 FROM Table WHERE JSON_EXISTS (jsonCol, '$.where')
=> PHOENIX-7099 : Implement JSON_EXISTS function on json object

phoenix-core/src/it/java/org/apache/phoenix/end2end/json/JsonFunctionsIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/ProjectionCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/coprocessor/BaseScannerRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/ExplainTable.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/NonAggregateRegionScannerFactory.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RegionScannerFactory.java
[PHOENIX-7073](https://issues.apache.org/jira/browse/PHOENIX-7073)
=> PHOENIX-7073 : Parse JSON columns on the server side

phoenix-core/src/main/java/org/apache/phoenix/coprocessor/MetaDataRegionObserver.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java
=> PHOENIX-7076 MetaDataRegionObserver#postOpen hook improvements 

phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core/src/test/java/org/apache/phoenix/cache/ServerMetadataCacheTest.java
[JIRA](https://issues.apache.org/jira/browse/PHOENIX-7167)
=> PHOENIX-7167 : Bootstrap LAST_DDL_TIMESTAMP for SYSTEM.CATALOG PTable object

phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCMiscIT.java, phoenix-core/src/main/antlr3/PhoenixSQL.g, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core/src/main/java/org/apache/phoenix/exception/SQLExceptionInfo.java, phoenix-core/src/main/java/org/apache/phoenix/index/IndexMaintainer.java, phoenix-core/src/main/java/org/apache/phoenix/iterate/RegionScannerFactory.java, phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixStatement.java, phoenix-core/src/main/java/org/apache/phoenix/optimize/QueryOptimizer.java, phoenix-core/src/main/java/org/apache/phoenix/parse/CreateCDCStatement.java, phoenix-core/src/main/java/org/apache/phoenix/parse/HintNode.java, phoenix-core/src/main/java/org/apache/phoenix/parse/ParseNodeFactory.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/main/java/org/apache/phoenix/schema/PTable.java, phoenix-core/src/main/java/org/apache/phoenix/schema/TableProperty.java, phoenix-core/src/main/java/org/apache/phoenix/util/CDCUtil.java, phoenix-core/src/test/java/org/apache/phoenix/parse/QueryParserTest.java, phoenix-core/src/test/java/org/apache/phoenix/util/CDCUtilTest.java
Address the changes in the CREATE CDC spec in PHOENIX-7001
Also includes some review feedback changes across the changes in PRs #1681, #1703 and #1766
=> PHOENIX-7008: Addressing Jira spec and review feedback changes

phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCMiscIT.java, phoenix-core/src/main/antlr3/PhoenixSQL.g, phoenix-core/src/test/java/org/apache/phoenix/parse/QueryParserTest.java
* Updates the parser to recognize the right tokens for include
* Fix for the failing test
* Jira: https://issues.apache.org/jira/browse/PHOENIX-7008
=> PHOENIX-7008: Fix for parser gap and a failing test

phoenix-core-client/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/pom.xml, phoenix-core/src/it/java/org/apache/phoenix/end2end/BloomFilterIT.java, phoenix-core/src/test/java/org/apache/phoenix/compile/WhereOptimizerTest.java, phoenix-core/src/test/java/org/apache/phoenix/util/TestUtil.java
=> PHOENIX-7229 Leverage bloom filters for single key point lookups

dev/create-release/README.txt, dev/create-release/do-release-docker.sh, dev/create-release/mac-sshd-gpg-agent/Dockerfile, dev/create-release/release-util.sh, phoenix-assembly/pom.xml, phoenix-client-parent/phoenix-client-embedded/pom.xml, phoenix-client-parent/phoenix-client-lite/pom.xml, phoenix-client-parent/pom.xml, phoenix-core-client/pom.xml, phoenix-core-client/src/main/java/org/apache/phoenix/coprocessorclient/MetaDataProtocol.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core-server/pom.xml, phoenix-core/pom.xml, phoenix-hbase-compat-2.4.1/pom.xml, phoenix-hbase-compat-2.5.0/pom.xml, phoenix-hbase-compat-2.5.4/pom.xml, phoenix-mapreduce-byo-shaded-hbase/pom.xml, phoenix-pherf/pom.xml, phoenix-server/pom.xml, phoenix-tracing-webapp/pom.xml, pom.xml
Jira: PHOENIX-7236
More details: [MGPG-92](https://issues.apache.org/jira/browse/MGPG-92)
=> PHOENIX-7236 Update version to 5.3.0 and fix issues with maven-gpg-plugin and gnupg (ADDENDUM)

phoenix-core-client/src/main/java/org/apache/phoenix/optimize/QueryOptimizer.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/RowValueConstructorOffsetIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TenantSpecificTablesDDLIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/PartialIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/index/UncoveredGlobalIndexRegionScannerIT.java
=> PHOENIX-7258: Query Optimizer should pick Index hint even for point lookup queries

phoenix-core-client/src/main/java/org/apache/phoenix/compile/ExplainPlanAttributes.java, phoenix-core-client/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core-client/src/main/java/org/apache/phoenix/iterate/DefaultParallelScanGrouper.java, phoenix-core-client/src/main/java/org/apache/phoenix/iterate/ParallelScanGrouper.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServices.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionlessQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/DelegateConnectionQueryServices.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core-server/src/main/java/org/apache/phoenix/iterate/MapReduceParallelScanGrouper.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/BaseTenantSpecificViewIndexIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ExplainPlanWithStatsDisabledIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TenantSpecificViewIndexSaltedIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/salted/SaltedTableIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixTableLevelMetricsIT.java, phoenix-core/src/it/resources/compatible_client_versions.json, phoenix-core/src/test/java/org/apache/phoenix/iterate/TestingMapReduceParallelScanGrouper.java, phoenix-core/src/test/java/org/apache/phoenix/query/ConnectionQueryServicesImplTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/QueryPlanTest.java
=> PHOENIX-7253 Metadata lookup performance improvement for range scan queries

phoenix-core-client/src/main/java/org/apache/phoenix/iterate/SerialIterators.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/ScanUtil.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ServerPagingIT.java
Fix paging for scans with limit but no other filter
=> PHOENIX-7302 Server Paging doesn't work on scans with limit

phoenix-core-client/src/main/java/org/apache/phoenix/iterate/BaseResultIterators.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TenantSpecificTablesDMLIT.java, phoenix-core/src/test/java/org/apache/phoenix/compile/WhereOptimizerTest.java
parent's PK but we do a point lookup using the parent's PK.
=> PHOENIX-7229 Addendum to handle cases where a child view extends the

phoenix-core-client/src/main/java/org/apache/phoenix/cache/ServerCacheClient.java, phoenix-core-client/src/main/java/org/apache/phoenix/iterate/DefaultParallelScanGrouper.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServices.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionlessQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/DelegateConnectionQueryServices.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServices.java, phoenix-core-server/src/main/java/org/apache/phoenix/iterate/MapReduceParallelScanGrouper.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MapReduceIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/SkipScanAfterManualSplitIT.java, phoenix-core/src/it/java/org/apache/phoenix/iterate/PhoenixQueryTimeoutIT.java, phoenix-core/src/it/java/org/apache/phoenix/iterate/RoundRobinResultIteratorIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/PhoenixTableLevelMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/schema/stats/BaseStatsCollectorIT.java, phoenix-core/src/test/java/org/apache/phoenix/cache/ServerCacheClientTest.java, phoenix-core/src/test/java/org/apache/phoenix/compile/QueryCompilerTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/ConnectionQueryServicesImplTest.java, phoenix-core/src/test/java/org/apache/phoenix/query/ParallelIteratorsSplitTest.java
=> PHOENIX-7306 Metadata lookup should be permitted only within query timeout

phoenix-core/src/it/java/org/apache/phoenix/end2end/ConcurrentMutationsExtendedIT.java, phoenix-core/src/main/java/org/apache/phoenix/hbase/index/IndexRegionObserver.java
=> PHOENIX-7245 NPE in Phoenix Coproc leading to Region Server crash

phoenix-core-client/src/main/java/org/apache/phoenix/compile/ExpressionCompiler.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/ExpressionType.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/function/JsonModifyFunction.java, phoenix-core-client/src/main/java/org/apache/phoenix/parse/JsonModifyParseNode.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/json/JsonFunctionsIT.java
=> PHOENIX-7072 : Implement json_modify function on the json object as Atomic Upserts

phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexRepairRegionScannerIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/IndexScrutinyWithMaxLookbackIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MaxLookbackExtendedIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MaxLookbackIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TableTTLIT.java
=> PHOENIX-7339 HBase flushes with custom clock needs to disable remote procedure delay

phoenix-core-client/src/main/java/org/apache/phoenix/schema/task/Task.java, phoenix-core-client/src/main/java/org/apache/phoenix/trace/PhoenixMetricsSink.java, phoenix-core-client/src/main/java/org/apache/phoenix/trace/TraceReader.java, phoenix-core-client/src/main/java/org/apache/phoenix/trace/TraceWriter.java, phoenix-core-server/src/main/java/org/apache/phoenix/mapreduce/index/automation/PhoenixMRJobSubmitter.java
=> PHOENIX-7316 Need close more Statements

phoenix-core-client/src/main/java/org/apache/phoenix/iterate/ExplainTable.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/FlappingLocalIndexIT.java
=> PHOENIX-7365 ExplainPlanV2 should get trimmed list for regionserver location

phoenix-core-client/src/main/java/org/apache/phoenix/exception/SQLExceptionCode.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryConstants.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CreateTableIT.java
(cherry picked from commit 1f88ca83f0efb576f01bdffb35becdc5ebccf58a)
=> PHOENIX-7309 Support specifying splits.txt file while creating a table

phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/schema/MetaDataSplitPolicy.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ConcurrentGetTablesIT.java
=> PHOENIX-7369 Avoid redundant recursive getTable() RPC calls

phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/schema/MetaDataSplitPolicy.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/ConcurrentGetTablesIT.java
=> PHOENIX-7369 Avoid redundant recursive getTable() RPC calls (#1944)

phoenix-core/src/it/java/org/apache/phoenix/end2end/MutationStateIT.java, phoenix-core/src/main/java/org/apache/phoenix/compile/UpsertCompiler.java, phoenix-core/src/main/java/org/apache/phoenix/schema/MaxPhoenixColumnSizeExceededException.java
Jira: [PHOENIX-7394](https://issues.apache.org/jira/browse/PHOENIX-7394)
=> PHOENIX-7394 MaxPhoenixColumnSizeExceededException should not print rowkey

phoenix-core-client/src/main/java/org/apache/phoenix/monitoring/GlobalClientMetrics.java, phoenix-core-client/src/main/java/org/apache/phoenix/monitoring/MetricType.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/PMetaDataCache.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/PMetaDataImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/metrics/MetricsMetadataSource.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/metrics/MetricsMetadataSourceImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/cache/GlobalCache.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MetaDataEndPointIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/IndexMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/monitoring/MetadataMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/query/MetaDataCacheMetricsIT.java, phoenix-core/src/it/java/org/apache/phoenix/query/MetaDataCachingIT.java
=> PHOENIX-7395 Metadata Cache metrics at server and client side

phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/CompactionScanner.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/UngroupedAggregateRegionObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MaxLookbackExtendedIT.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/TableTTLIT.java, phoenix-core/src/test/java/org/apache/phoenix/util/TestUtil.java
Cherry-pick of: https://github.com/apache/phoenix/pull/1973
=> PHOENIX-7402: Fix row getting expired partially even if updated within TTL

phoenix-core-client/pom.xml, phoenix-core-client/src/main/java/org/apache/phoenix/util/InstanceResolver.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/QueryBuilder.java, phoenix-core/pom.xml, phoenix-core/src/it/java/org/apache/phoenix/end2end/TableSnapshotReadsMapReduceIT.java, phoenix-tracing-webapp/src/build/trace-server-runnable.xml, pom.xml
- Remove imports and replace with equivalent code
- Add RestrictImports rule to restrict further usage of it in codebase
=> PHOENIX-7417 Remove commons-collections dependency

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/ConnectionInfo.java
Creating this PR for one of the solution of JIRA (Caching configuration at ConnectionInfo level as each CQSI can have different confs)
=> PHOENIX-7464 :- Performance Regression in Connection Initialization due to Configuration Handling in ConnInfo

phoenix-core-client/src/main/java/org/apache/phoenix/execute/BaseQueryPlan.java, phoenix-core-client/src/main/java/org/apache/phoenix/execute/HashJoinPlan.java, phoenix-core-client/src/main/java/org/apache/phoenix/execute/LiteralResultIterationPlan.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/UnionAllIT.java
PHOENIX-7492: Need to clear the dependencies once it is closed, to avoid null pointer in future
Change-Id: Ifba79d894e20d0abd12382f969cdc1dd5119bd36
=> PHOENIX-7492: Need to clear the dependencies once it is closed

phoenix-core/src/it/java/org/apache/phoenix/end2end/UnionAllIT.java, phoenix-core/src/main/java/org/apache/phoenix/execute/BaseQueryPlan.java, phoenix-core/src/main/java/org/apache/phoenix/execute/HashJoinPlan.java, phoenix-core/src/main/java/org/apache/phoenix/execute/LiteralResultIterationPlan.java
[PHOENIX-7492](https://issues.apache.org/jira/browse/PHOENIX-7492): Need to clear the dependencies once it is closed, to avoid null pointer in future
=> PHOENIX-7492: Need to clear the dependencies once it is closed (#2044)

phoenix-core-client/src/main/java/org/apache/phoenix/compile/JoinCompiler.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/MixedCaseInnerJoinAliasesIT.java
Cherry picked changes for master.
=> PHOENIX-7491 Mixed-cased alias doesn't work in select statement of “INNER JOIN"

phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryConstants.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/PhoenixMasterObserver.java
=> PHOENIX-7500 : Add PARENT_PARTITION_ID to SYSTEM.CDC_STREAM table's composite pk

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/PhoenixResultSet.java, phoenix-core/src/test/java/TimeZoneDisplacementIT.java
Should not applyOutputDisplacement when value is null
=> PHOENIX-7494 NPE thrown when enable applyTimeZone

pom.xml
=> PHOENIX-7547 : Upgrade BSON version to 5.3.1

phoenix-core-client/src/main/java/org/apache/phoenix/schema/CompiledConditionalTTLExpression.java, phoenix-core/src/it/java/org/apache/phoenix/schema/ConditionalTTLExpressionIT.java, phoenix-core/src/test/java/org/apache/phoenix/schema/ConditionalTTLExpressionTest.java
Fix how we construct the latestRowVersion from the raw scan to evaluate the TTL expression.
=> PHOENIX-7170 Conditional TTL (addendum)

phoenix-core-client/src/main/java/org/apache/phoenix/compile/ScanRanges.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/salted/SaltedTableWithParallelStatsEnabledIT.java, phoenix-core/src/test/java/org/apache/phoenix/query/BaseTest.java
Cherry-pick of: https://github.com/apache/phoenix/pull/2109
=> PHOENIX-7580: Data in last salt bucket is not being scanned for range scan

phoenix-core/src/it/java/org/apache/phoenix/end2end/salted/SaltedTableWithParallelStatsEnabledIT.java
Fixing Scan API incompatibility with HBase 2.4 introduced in https://github.com/apache/phoenix/pull/2109
=> PHOENIX-7580: ADDENDUM to fix compatibility with HBase 2.4 build

phoenix-core-client/src/main/java/org/apache/phoenix/expression/ExpressionType.java, phoenix-core-client/src/main/java/org/apache/phoenix/expression/function/SubBinaryFunction.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/SubBinaryFunctionIT.java
[PHOENIX-7588](https://issues.apache.org/jira/browse/PHOENIX-7588)
=> PHOENIX-7588 : SUBBINARY() - Substring like function for Binary data types

phoenix-core-client/src/main/java/org/apache/phoenix/schema/types/PBson.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/ByteUtil.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/json/BsonDataFormat.java
=> PHOENIX-7617 BSON serialization should retain ByteBuffer offset

.gitignore, phoenix-core-client/src/main/java/org/apache/phoenix/expression/function/BsonValueFunction.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/Bson4IT.java
=> PHOENIX-7631 BSON_VALUE() to support returning binary value with VARBINARY_ENCODED data type encoding

phoenix-core-client/src/main/java/org/apache/phoenix/jdbc/HighAvailabilityPolicy.java, phoenix-core/src/it/java/org/apache/phoenix/jdbc/FailoverPhoenixConnection2IT.java
Closing connections when we transition to either Standby or Active_To_Standby instead of closing it at Standby only.
=> PHOENIX-7586 (ADDENDUM) :- Handle Role transitions for ActiveToStanby role in Failover HAPolicy

phoenix-core-client/src/main/java/org/apache/phoenix/execute/TupleProjector.java, phoenix-core-client/src/main/java/org/apache/phoenix/filter/MultiEncodedCQKeyValueComparisonFilter.java, phoenix-core-client/src/main/java/org/apache/phoenix/filter/MultiKeyValueComparisonFilter.java, phoenix-core-client/src/main/java/org/apache/phoenix/filter/RowKeyComparisonFilter.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/BaseTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/DelegateTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/MultiKeyValueTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/PositionBasedMultiKeyValueTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/PositionBasedResultTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/ResultTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/SingleKeyValueTuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/Tuple.java, phoenix-core-client/src/main/java/org/apache/phoenix/schema/tuple/ValueGetterTuple.java, phoenix-core/src/test/java/org/apache/phoenix/schema/tuple/TupleKeyValueBytesSizeTest.java
=> PHOENIX-7633 Tuple API to provide serialized bytes size for the given Tuple

phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryConstants.java, phoenix-core-client/src/main/java/org/apache/phoenix/util/CDCUtil.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/MetaDataEndpointImpl.java, phoenix-core-server/src/main/java/org/apache/phoenix/coprocessor/PhoenixMasterObserver.java, phoenix-core/src/it/java/org/apache/phoenix/end2end/CDCDefinitionIT.java
1. Remove CDC Object from SYSTEM.CATALOG when table is dropped
2. Set UCF=2h on CDC streams system tables.
3. try-with-resource for PhoenixMasterObserver
=> PHOENIX-7644 : CDC Stream improvements

phoenix-core-client/src/main/java/org/apache/phoenix/schema/MetaDataClient.java
=> PHOENIX-7442 Apply Spotless to reformat the entire codebase (Addendum)

src/main/config/checkstyle/checker.xml
Jira: PHOENIX-7676
- Sync `ImportOrder` groups based on `dev/phoenix.importorder`
- Sync `Indentation` rules with HBase
=> PHOENIX-7676 Update checkstyle checker.xml based on spotless rules

phoenix-core-client/src/main/java/org/apache/phoenix/query/ConnectionQueryServicesImpl.java, phoenix-core-client/src/main/java/org/apache/phoenix/query/QueryServicesOptions.java
Co-authored-by: David Manning <david.manning@salesforce.com>
Jira: PHOENIX-7700
=> PHOENIX-7700 Update default values for schema change retry policy
